# Generated by Django 4.0.4 on 2022-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corporatemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2)),
                ('employees', models.IntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
