# Generated by Django 4.0.4 on 2022-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='corporates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('opennings', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2)),
                ('employees', models.IntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.DeleteModel(
            name='corporatemodel',
        ),
    ]
