# Generated by Django 4.0.4 on 2022-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_corporates_delete_corporatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporates',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='corporates',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
